[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8000
# Open a browser tab once the initial build is complete.
open = true

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:8080/"