name: CI
on:
  push:
    branches: [ main ]
    tags:
      - v*

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: build
        run: cargo build --verbose
      - name: run tests
        run: cargo test --verbose
  publish:
    name: publish to Docker
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: create container and publish to Docker Hub
      uses: hannes-hochreiner/gha-publish-on-docker-hub@v1.5.0
      with:
        docker-user-name: ${{ secrets.DOCKER_USER }}
        docker-token: ${{ secrets.DOCKER_TOKEN }}